from __future__ import annotations
from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID, uuid4
from pydantic import BaseModel, Field


class ConfidenceLevel(str, Enum):
    HIGH = "high"           # 3+ corroborating sources
    MEDIUM = "medium"       # 2 sources or 1 strong source
    LOW = "low"             # 1 weak source or inferred
    UNCERTAIN = "uncertain" # Flagged but unverifiable


class ConflictFlag(BaseModel):
    """Potential conflict or competing interest — always a flag for review, never clearance."""
    description: str
    related_entity: str
    severity: str  # "review_required" | "potential_issue" | "monitor"
    note: str = "This is a flag for review only. Not a conflicts clearance."


class CommercialTrigger(BaseModel):
    """Why this matters NOW — the time-sensitive commercial reason."""
    trigger: str                            # e.g. "Series B closing in 6 weeks"
    urgency: str                            # "immediate" | "near_term" | "monitor"
    connected_clients: list[str] = Field(default_factory=list)
    estimated_opportunity: Optional[str] = None   # e.g. "$3.8M–$5.2M"
    opportunity_assumptions: list[str] = Field(default_factory=list)


class SuggestedApproach(BaseModel):
    action: str             # What the firm could reasonably do
    rationale: str
    priority: str           # "high" | "medium" | "low"


class OpportunityBrief(BaseModel):
    """
    A structured brief generated by Verity when it surfaces something worth attention.
    Every field must be traceable to evidence. No unsupported claims.
    """
    id: UUID = Field(default_factory=uuid4)
    title: str                                  # e.g. "Meridian Infrastructure — Series B closing in 6 weeks"
    entity_name: str
    entity_id: Optional[UUID] = None

    # Evidence — what happened and what supports it
    what_happened: str                          # Plain English summary
    evidence_summary: list[str]                 # Each item = one piece of evidence with source
    confidence: ConfidenceLevel

    # Conflict check — always a flag, never clearance
    conflict_flags: list[ConflictFlag] = Field(default_factory=list)
    conflict_check_note: str = (
        "Conflict flags are for review only. Verity does not provide conflicts clearance."
    )

    # Commercial trigger
    commercial_trigger: CommercialTrigger

    # Suggested approach
    suggested_approaches: list[SuggestedApproach] = Field(default_factory=list)

    # Financial analysis (where evidence supports it)
    financial_analysis: Optional[str] = None
    financial_assumptions: list[str] = Field(default_factory=list)

    # Meets firm criteria?
    meets_firm_criteria: Optional[bool] = None
    criteria_assessment: Optional[str] = None

    # Meta
    change_event_id: Optional[UUID] = None
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    reviewed: bool = False
    reviewer_notes: Optional[str] = None
